version: "2"
services:
  zookeeper:
    network_mode: host
    container_name: zookeeper
    image: ucamcldtg/zookeeper
    restart: always
    logging:
      driver: journald
      options:
        tag: zookeeper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /local/data/zookeeper:/zookeeper-data:rw
      - ./zoo.cfg:/opt/zookeeper/conf/zoo.cfg:ro

